# Generated by Django 4.2.3 on 2023-08-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('coordinate', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Locations',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('start_point', models.CharField(max_length=100)),
                ('destination_point', models.CharField(max_length=100)),
                ('receiver', models.CharField(default='None', max_length=255, null=True)),
                ('status', models.BooleanField()),
            ],
            options={
                'db_table': 'Requests',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UsersYa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10)),
                ('group', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'UsersYa',
                'managed': True,
            },
        ),
    ]
