# Generated by Django 4.2.3 on 2023-08-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_go', '0002_locations_adress_requests_order_alter_locations_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='login',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='usersya',
            name='chosen_city',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
