# Generated by Django 4.2.3 on 2023-08-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_go', '0004_remove_locations_login_usersya_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersya',
            name='yandex_id',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
