# Generated by Django 4.2 on 2023-08-08 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_go', '0005_usersya_yandex_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requests',
            name='receiver',
        ),
        migrations.AlterField(
            model_name='requests',
            name='destination_point',
            field=models.CharField(default='None', max_length=255, null=True),
        ),
    ]
