# Generated by Django 4.2.2 on 2023-06-29 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=50)),
                ('requested_equipment', models.TextField()),
                ('avtor', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('deadline', models.DateField()),
                ('department', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, choices=[('готов к выдаче', 'Готов к выдаче'), ('закуп', 'Закуп'), ('на заточке', 'На заточке')], max_length=100)),
            ],
        ),
    ]
