# Generated by Django 4.2 on 2023-10-11 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('num', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('requested_equipment', models.TextField(blank=True, null=True)),
                ('avtor', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('deadline', models.DateField(blank=True, default=None, null=True)),
                ('department', models.CharField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(blank=True, choices=[('готов к выдаче', 'Готов к выдаче'), ('закуп', 'Закуп'), ('необходимо заточить', 'Необходимо заточить'), ('на заточке', 'На заточке'), ('завершена', 'Завершена')], max_length=100, null=True)),
            ],
            options={
                'db_table': 'Applications',
                'managed': True,
            },
        ),
    ]
