# Generated by Django 4.2 on 2023-09-11 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_applications_deadline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applications',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='applications',
            name='status',
            field=models.CharField(blank=True, choices=[('готов к выдаче', 'Готов к выдаче'), ('закуп', 'Закуп'), ('необходимо заточить', 'Необходимо заточить'), ('на заточке', 'На заточке'), ('завершена', 'Завершена')], max_length=100),
        ),
        migrations.AlterModelTable(
            name='applications',
            table='Applications',
        ),
    ]
