# Generated by Django 4.2 on 2023-09-11 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_applications_options_alter_applications_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applications',
            name='id',
        ),
        migrations.AlterField(
            model_name='applications',
            name='num',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
