# Generated by Django 4.2 on 2023-09-11 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_remove_applications_id_alter_applications_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
