# Generated by Django 4.2 on 2023-09-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_alter_applications_avtor_alter_applications_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='requested_equipment',
            field=models.TextField(null=True),
        ),
    ]
