# Generated by Django 4.2 on 2023-09-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_alter_applications_requested_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='avtor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='applications',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applications',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='applications',
            name='requested_equipment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applications',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
