# Generated by Django 4.2 on 2023-09-12 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_alter_applications_avtor_alter_applications_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='avtor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='applications',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applications',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='applications',
            name='requested_equipment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applications',
            name='status',
            field=models.CharField(blank=True, choices=[('готов к выдаче', 'Готов к выдаче'), ('закуп', 'Закуп'), ('необходимо заточить', 'Необходимо заточить'), ('на заточке', 'На заточке'), ('завершена', 'Завершена')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='applications',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
