# Generated by Django 4.2 on 2023-09-12 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_alter_applications_avtor_alter_applications_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
