# Generated by Django 4.2.3 on 2023-09-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0013_alter_applications_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='department',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
