# Generated by Django 4.2 on 2023-09-20 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0014_alter_applications_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
