# Generated by Django 4.2 on 2023-09-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0015_alter_applications_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='status',
            field=models.CharField(blank=True, choices=[('готов к выдаче', 'Готов к выдаче'), ('закуп', 'Закуп'), ('необходимо заточить', 'Необходимо заточить'), ('на заточке', 'На заточке'), ('завершена', 'Завершена')], default=('закуп', 'Закуп'), max_length=100, null=True),
        ),
    ]
