# Generated by Django 4.2 on 2023-09-21 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0017_alter_applications_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='deadline',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
