# Generated by Django 4.2 on 2023-10-11 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avtor', models.CharField(max_length=101)),
                ('type', models.CharField(max_length=100)),
                ('result', models.CharField(max_length=255)),
                ('conclusion', models.CharField(max_length=255)),
                ('act_date', models.DateField(auto_now_add=True)),
                ('user', models.CharField(blank=True, max_length=255, null=True)),
                ('sklad', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255)),
                ('inv_dit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='directories.it_os')),
                ('new_sklad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='directories.skladyoffice')),
                ('new_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='directories.users')),
            ],
            options={
                'db_table': 'Acts',
                'managed': True,
            },
        ),
    ]
