# Generated by Django 4.2.2 on 2023-07-10 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0002_alter_it_os_inpute_date_alter_it_os_original_price_and_more'),
        ('acts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acts',
            old_name='act_type',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='acts',
            name='os',
        ),
        migrations.AddField(
            model_name='acts',
            name='inv_dit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='directories.it_os'),
        ),
    ]
