# Generated by Django 4.2 on 2023-10-26 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActsSkan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_file', models.FileField(upload_to='uploads/acts/')),
                ('act_num', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acts.acts')),
            ],
        ),
    ]
