# Generated by Django 4.2 on 2023-08-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0003_acts_other_tech_acts_status_alter_acts_inv_dit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acts',
            name='other_tech',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
