# Generated by Django 4.2 on 2023-08-04 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0004_alter_acts_other_tech'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acts',
            name='other_tech',
        ),
    ]
