# Generated by Django 4.2.3 on 2023-08-07 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0003_acts_status_alter_acts_inv_dit'),
        ('acts', '0005_remove_acts_other_tech'),
    ]

    operations = [
    ]
