# Generated by Django 4.2 on 2023-08-08 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0006_merge_20230807_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='acts',
            name='user_lower',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
