# Generated by Django 4.2 on 2023-08-08 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0007_acts_user_lower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acts',
            name='user_lower',
        ),
    ]
