# Generated by Django 4.2.3 on 2023-09-15 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0009_alter_acts_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acts',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
