# Generated by Django 4.2.3 on 2023-09-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0010_alter_acts_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acts',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
