# Generated by Django 4.2.3 on 2023-09-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0011_alter_acts_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acts',
            name='sklad',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='acts',
            name='user',
            field=models.CharField(max_length=255),
        ),
    ]
