# Generated by Django 4.2.3 on 2023-09-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0012_alter_acts_sklad_alter_acts_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acts',
            name='status',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
