# Generated by Django 4.2.3 on 2023-09-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0013_alter_acts_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acts',
            name='status',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
