# Generated by Django 4.2.3 on 2023-09-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0014_alter_acts_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acts',
            name='avtor',
            field=models.CharField(max_length=101),
        ),
    ]
