# Generated by Django 4.2.3 on 2023-09-19 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0015_alter_acts_avtor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acts',
            name='inv_dit',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
