# Generated by Django 4.2.3 on 2023-09-20 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0023_alter_skladyoffice_sklad_name_lower'),
        ('acts', '0016_alter_acts_inv_dit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acts',
            name='inv_dit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='directories.it_os'),
        ),
    ]
