# Generated by Django 4.2.1 on 2023-10-10 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0028_alter_it_os_os_group'),
        ('acts', '0017_alter_acts_inv_dit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acts',
            name='sklad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directories.skladyoffice'),
        ),
        migrations.AlterField(
            model_name='acts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directories.users'),
        ),
        migrations.CreateModel(
            name='OldActs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avtor', models.CharField(max_length=101)),
                ('type', models.CharField(max_length=100)),
                ('result', models.CharField(max_length=255)),
                ('conclusion', models.CharField(max_length=255)),
                ('act_date', models.DateField(auto_now_add=True)),
                ('user', models.CharField(max_length=255)),
                ('sklad', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, max_length=255)),
                ('inv_dit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='directories.it_os')),
            ],
            options={
                'db_table': 'OldActs',
                'managed': True,
            },
        ),
    ]
