# Generated by Django 4.2.1 on 2023-10-10 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0028_alter_it_os_os_group'),
        ('acts', '0017_alter_acts_inv_dit'),
    ]

    operations = [
        migrations.AddField(
            model_name='acts',
            name='new_sklad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='directories.skladyoffice'),
        ),
        migrations.AddField(
            model_name='acts',
            name='new_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='directories.users'),
        ),
    ]
