# Generated by Django 4.2.1 on 2023-10-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0018_acts_new_sklad_acts_new_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acts',
            name='sklad',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='acts',
            name='user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
