# Generated by Django 4.2.1 on 2023-10-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0018_alter_acts_sklad_alter_acts_user_oldacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oldacts',
            name='inv_dit',
        ),
        migrations.AddField(
            model_name='oldacts',
            name='inv_dit_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
