# Generated by Django 4.2.1 on 2023-10-10 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0019_alter_acts_sklad_alter_acts_user'),
        ('acts', '0019_remove_oldacts_inv_dit_oldacts_inv_dit_id'),
    ]

    operations = [
    ]
