# Generated by Django 4.2.1 on 2023-10-10 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0020_merge_20231010_2125'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OldActs',
        ),
    ]
