# Generated by Django 4.2 on 2023-10-11 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directories', '0001_initial'),
        ('acts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TmcMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_num', models.CharField(max_length=20, null=True)),
                ('move_date', models.DateField(null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('avtor', models.CharField(max_length=100)),
                ('sklad', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=255, null=True)),
                ('qty', models.IntegerField(null=True)),
                ('equipment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='directories.tmc')),
                ('par_dok', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='acts.acts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directories.users')),
            ],
            options={
                'db_table': 'TMC_move',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OsMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_num', models.CharField(max_length=20, null=True)),
                ('move_date', models.DateField(null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('avtor', models.CharField(max_length=100)),
                ('sklad', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=255, null=True)),
                ('equipment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='directories.it_os')),
                ('par_dok', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='acts.acts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directories.users')),
            ],
            options={
                'db_table': 'OS_move',
                'managed': True,
            },
        ),
    ]
