# Generated by Django 4.2.1 on 2023-06-20 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TmcMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_num', models.CharField(max_length=20, null=True)),
                ('move_date', models.DateField()),
                ('status', models.BooleanField()),
                ('avtor', models.CharField(max_length=100)),
                ('qty', models.IntegerField()),
                ('comment', models.CharField(max_length=255, null=True)),
                ('equipment', models.ManyToManyField(to='directories.tmc')),
                ('sklad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directories.skladyoffice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directories.users')),
            ],
            options={
                'db_table': 'TMC_move',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OsMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_num', models.CharField(max_length=20, null=True)),
                ('move_date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('avtor', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=255, null=True)),
                ('equipment', models.ManyToManyField(to='directories.it_os')),
                ('sklad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='directories.skladyoffice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directories.users')),
            ],
            options={
                'db_table': 'OS_move',
                'managed': True,
            },
        ),
    ]
