# Generated by Django 4.2.2 on 2023-07-10 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0002_alter_it_os_inpute_date_alter_it_os_original_price_and_more'),
        ('moves', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osmove',
            name='move_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tmcmove',
            name='move_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tmcmove',
            name='sklad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='directories.skladyoffice'),
        ),
        migrations.AlterField(
            model_name='tmcmove',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
