# Generated by Django 4.2 on 2023-08-03 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moves', '0002_alter_osmove_move_date_alter_tmcmove_move_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='osmove',
            old_name='equipment',
            new_name='equipment_os',
        ),
        migrations.RenameField(
            model_name='tmcmove',
            old_name='equipment',
            new_name='equipment_tmc',
        ),
    ]
