# Generated by Django 4.2.1 on 2023-08-13 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0008_remove_acts_user_lower'),
        ('moves', '0003_rename_equipment_osmove_equipment_os_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='osmove',
            name='par_dok',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='acts.acts'),
        ),
        migrations.AddField(
            model_name='tmcmove',
            name='par_dok',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='acts.acts'),
        ),
    ]
