# Generated by Django 4.2 on 2023-08-31 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0008_remove_acts_user_lower'),
        ('moves', '0004_osmove_par_dok_tmcmove_par_dok'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osmove',
            name='par_dok',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='acts.acts'),
        ),
        migrations.AlterField(
            model_name='tmcmove',
            name='par_dok',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='acts.acts'),
        ),
    ]
