# Generated by Django 4.2 on 2023-09-13 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0015_alter_tmc_tmc_price'),
        ('moves', '0005_alter_osmove_par_dok_alter_tmcmove_par_dok'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='osmove',
            name='equipment_os',
        ),
        migrations.AddField(
            model_name='osmove',
            name='equipment_os',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='directories.it_os'),
        ),
    ]
