# Generated by Django 4.2 on 2023-09-13 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moves', '0006_remove_osmove_equipment_os_osmove_equipment_os'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osmove',
            name='move_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='tmcmove',
            name='move_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
