# Generated by Django 4.2 on 2023-09-13 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moves', '0007_alter_osmove_move_date_alter_tmcmove_move_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osmove',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tmcmove',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
