# Generated by Django 4.2 on 2023-09-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moves', '0009_rename_equipment_os_osmove_equipment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osmove',
            name='move_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tmcmove',
            name='move_date',
            field=models.DateField(null=True),
        ),
    ]
