# Generated by Django 4.2 on 2023-09-13 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0015_alter_tmc_tmc_price'),
        ('moves', '0010_alter_osmove_move_date_alter_tmcmove_move_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tmcmove',
            name='equipment',
        ),
        migrations.AddField(
            model_name='tmcmove',
            name='equipment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='directories.tmc'),
        ),
    ]
