# Generated by Django 4.2 on 2023-09-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moves', '0011_remove_tmcmove_equipment_tmcmove_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmcmove',
            name='qty',
            field=models.IntegerField(null=True),
        ),
    ]
