# Generated by Django 4.2.1 on 2023-09-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moves', '0012_alter_tmcmove_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osmove',
            name='sklad',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tmcmove',
            name='equipment',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tmcmove',
            name='sklad',
            field=models.CharField(max_length=100),
        ),
    ]
