# Generated by Django 4.2 on 2023-09-14 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0015_alter_tmc_tmc_price'),
        ('moves', '0013_alter_osmove_sklad_alter_tmcmove_equipment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmcmove',
            name='equipment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='directories.tmc'),
        ),
    ]
