# Generated by Django 4.2 on 2023-09-18 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moves', '0014_alter_tmcmove_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmcmove',
            name='equipment',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
