# Generated by Django 4.2 on 2023-09-18 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0019_alter_tmc_tmc_name_alter_tmc_web_code'),
        ('moves', '0015_alter_tmcmove_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmcmove',
            name='equipment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='directories.tmc'),
        ),
    ]
