# Generated by Django 4.2.1 on 2023-06-15 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avtor',
            fields=[
                ('avtor_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('avtor_doljnost', models.CharField(max_length=50)),
                ('avtor_otdel', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'avtor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='IT_OS',
            fields=[
                ('inv_dit', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name_os', models.CharField(max_length=100)),
                ('inpute_date', models.DateField()),
                ('os_group', models.CharField(max_length=100)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'IT_OS',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OsGroup',
            fields=[
                ('group_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'OS_Group',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tmc',
            fields=[
                ('tmc_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('tmc_article', models.CharField(max_length=50)),
                ('web_code', models.CharField(max_length=50)),
                ('tmc_price', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            options={
                'db_table': 'Tmc',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=50)),
                ('dad_name', models.CharField(max_length=50)),
                ('login', models.CharField(max_length=50)),
                ('phone_num', models.CharField(max_length=15)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SkladyOffice',
            fields=[
                ('sklad_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('sklad_type', models.CharField(max_length=50)),
                ('sklad_city', models.CharField(blank=True, max_length=50, null=True)),
                ('sklad_adress', models.CharField(max_length=100)),
                ('responsible_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='directories.users')),
            ],
            options={
                'db_table': 'Sklady_Office',
                'managed': True,
            },
        ),
    ]
