# Generated by Django 4.2 on 2023-10-11 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avtor',
            fields=[
                ('avtor_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('avtor_doljnost', models.CharField(max_length=50)),
                ('avtor_otdel', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'avtor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='IT_OS',
            fields=[
                ('inv_dit', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name_os', models.CharField(default='None', max_length=255)),
                ('inpute_date', models.DateTimeField(null=True)),
                ('os_group', models.CharField(max_length=100, null=True)),
                ('serial_number', models.CharField(default='None', max_length=255, null=True)),
                ('original_price', models.FloatField(default='100')),
            ],
            options={
                'db_table': 'IT_OS',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OsGroup',
            fields=[
                ('group_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'OS_Group',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SkladyOffice',
            fields=[
                ('sklad_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('sklad_type', models.CharField(blank=True, choices=[('офис', 'Офис'), ('региональный склад', 'Региональный склад'), ('лц', 'ЛЦ'), ('магазин', 'Магазин'), ('пвз', 'ПВЗ')], max_length=50)),
                ('sklad_city', models.CharField(blank=True, max_length=50, null=True)),
                ('sklad_adress', models.CharField(max_length=100)),
                ('sklad_name_lower', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Sklady_Office',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tmc',
            fields=[
                ('tmc_name', models.CharField(max_length=50)),
                ('tmc_article', models.CharField(max_length=50)),
                ('web_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('tmc_price', models.FloatField(default=100)),
            ],
            options={
                'db_table': 'Tmc',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=100, null=True)),
                ('position', models.CharField(max_length=255, null=True)),
                ('organization', models.CharField(max_length=255, null=True)),
                ('subdivision', models.CharField(max_length=255, null=True)),
                ('name_lower', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'Users',
                'managed': True,
            },
        ),
    ]
