# Generated by Django 4.2.2 on 2023-07-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='it_os',
            name='inpute_date',
            field=models.DateTimeField(default='None', null=True),
        ),
        migrations.AlterField(
            model_name='it_os',
            name='original_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='it_os',
            name='serial_number',
            field=models.CharField(default='None', max_length=255, null=True),
        ),
    ]
