# Generated by Django 4.2.2 on 2023-07-11 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0003_alter_it_os_original_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='it_os',
            name='inpute_date',
            field=models.DateTimeField(null=True),
        ),
    ]
