# Generated by Django 4.2 on 2023-08-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0005_alter_it_os_original_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='dad_name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='last_name',
        ),
        migrations.AddField(
            model_name='it_os',
            name='department',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='it_os',
            name='user',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='position',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='skladyoffice',
            name='sklad_type',
            field=models.CharField(blank=True, choices=[('цо', 'ЦО'), ('региональный склад', 'Региональный склад'), ('лц', 'ЛЦ'), ('магазин', 'Магазин'), ('пвз', 'ПВЗ')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tmc',
            name='tmc_price',
            field=models.FloatField(default='100'),
        ),
        migrations.AlterField(
            model_name='users',
            name='department',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='login',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone_num',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
