# Generated by Django 4.2 on 2023-08-04 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0009_alter_it_os_name_os_alter_it_os_os_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='it_os',
            name='name_os',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
