# Generated by Django 4.2.3 on 2023-08-07 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0007_alter_it_os_name_os_alter_it_os_os_group'),
        ('directories', '0011_alter_it_os_name_os'),
    ]

    operations = [
    ]
