# Generated by Django 4.2 on 2023-08-08 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0012_merge_20230807_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='name_lower',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
