# Generated by Django 4.2 on 2023-08-08 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0013_users_name_lower'),
    ]

    operations = [
        migrations.AddField(
            model_name='skladyoffice',
            name='sklad_name_lower',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
