# Generated by Django 4.2 on 2023-08-11 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0014_skladyoffice_sklad_name_lower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmc',
            name='tmc_price',
            field=models.FloatField(default=100),
        ),
    ]
