# Generated by Django 4.2.3 on 2023-09-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0015_alter_tmc_tmc_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='it_os',
            name='original_price',
            field=models.FloatField(default='100', null=True),
        ),
    ]
