# Generated by Django 4.2.3 on 2023-09-14 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0016_alter_it_os_original_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='it_os',
            name='original_price',
            field=models.FloatField(default='100'),
        ),
        migrations.AlterField(
            model_name='it_os',
            name='os_group',
            field=models.CharField(max_length=100),
        ),
    ]
