# Generated by Django 4.2.3 on 2023-09-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0017_alter_it_os_original_price_alter_it_os_os_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='it_os',
            name='name_os',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
