# Generated by Django 4.2 on 2023-09-18 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0018_alter_it_os_name_os'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmc',
            name='tmc_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tmc',
            name='web_code',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
