# Generated by Django 4.2 on 2023-09-18 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0019_alter_tmc_tmc_name_alter_tmc_web_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skladyoffice',
            name='responsible_person',
        ),
    ]
