# Generated by Django 4.2.3 on 2023-09-18 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0021_alter_skladyoffice_sklad_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='it_os',
            name='department',
        ),
        migrations.RemoveField(
            model_name='it_os',
            name='user',
        ),
    ]
