# Generated by Django 4.2.3 on 2023-09-19 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0022_remove_it_os_department_remove_it_os_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skladyoffice',
            name='sklad_name_lower',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
