# Generated by Django 4.2 on 2023-10-03 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0023_alter_skladyoffice_sklad_name_lower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='login',
        ),
        migrations.RemoveField(
            model_name='users',
            name='phone_num',
        ),
        migrations.AddField(
            model_name='users',
            name='organization',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='subdivision',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
