# Generated by Django 4.2.1 on 2023-10-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0024_remove_users_login_remove_users_phone_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
