# Generated by Django 4.2.1 on 2023-10-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0027_alter_users_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='it_os',
            name='os_group',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
