# Generated by Django 4.2.1 on 2023-06-15 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acts', '0001_initial'),
        ('directories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complectations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avtor', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('tmc_qty', models.IntegerField(max_length=4)),
                ('new_name_os', models.CharField(max_length=255)),
                ('spisanie_tmc_1c', models.CharField(max_length=12)),
                ('compl_os_1c', models.CharField(max_length=12)),
                ('inv_dit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directories.it_os')),
                ('par_doc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acts.acts')),
                ('tmc', models.ManyToManyField(to='directories.tmc')),
            ],
            options={
                'db_table': 'Complectations',
                'managed': True,
            },
        ),
    ]
