# Generated by Django 4.2.2 on 2023-07-10 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0002_alter_it_os_inpute_date_alter_it_os_original_price_and_more'),
        ('acts', '0002_rename_act_type_acts_type_remove_acts_os_and_more'),
        ('complectations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complectations',
            name='compl_os_1c',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='complectations',
            name='par_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='acts.acts'),
        ),
        migrations.AlterField(
            model_name='complectations',
            name='spisanie_tmc_1c',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='complectations',
            name='tmc',
            field=models.ManyToManyField(blank=True, to='directories.tmc'),
        ),
        migrations.AlterField(
            model_name='complectations',
            name='tmc_qty',
            field=models.IntegerField(),
        ),
    ]
