# Generated by Django 4.2 on 2023-08-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complectations', '0003_remove_complectations_compl_os_1c_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complectations',
            name='prev_name_os',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
