# Generated by Django 4.2 on 2023-08-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complectations', '0004_complectations_prev_name_os'),
    ]

    operations = [
        migrations.AddField(
            model_name='complectations',
            name='doc_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
