# Generated by Django 4.2 on 2023-08-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complectations', '0005_complectations_doc_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complectations',
            name='doc_num',
            field=models.IntegerField(blank=True),
        ),
    ]
