# Generated by Django 4.2 on 2023-08-11 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complectations', '0006_alter_complectations_doc_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complectations',
            name='doc_num',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
