# Generated by Django 4.2 on 2023-09-18 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0019_alter_tmc_tmc_name_alter_tmc_web_code'),
        ('complectations', '0007_alter_complectations_doc_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complectations',
            name='tmc',
        ),
        migrations.AddField(
            model_name='complectations',
            name='tmc',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, to='directories.tmc'),
        ),
    ]
